### ISSUE TITLE
Change np.array creation to include dtype

### ISSUE THREAD

**Issue by yonMaor** [vinsburg/alluvial_diagram#12]
We are currently getting a VisibleDeprecationWarning when running our examples.

In newer versions of numpy, creating an array using np.array must include a dtype specification. 
We need to change the creation of the numpy array in AlluvialTools.generate_alluvial_fan()

**Comment by Lakshayainani** [comment]
Can I take this up?
And does np.array for only the specified function AlluvialTools.generate_alluvial_fan() needs to be changed or for all the np.array usage ?

**Comment by vinsburg** [comment]
Realising that the code is a complete mess, I've decided to go for a different approach.
I'll change the data type for the alluvial_fan variable to better reflect it's purpose.
See [the related commit](https://github.com/vinsburg/alluvial_diagram/commit/3c94ec5d49540c09a699c9ea6c97d9bd9078630a).

This issue is no longer relevant but there are many other warnings and issues to address.
ATM I prefer to resolve most of these myself.
If you open a PR for an unresolved issue, I'll be inclined to adopt your solution.

Thank you both for bringing this to my attention and discussing the problem!
